root: true
extends:
  - "@garoudev/eslint-config"
env:
  es6: true
  node: true
ignorePatterns:
  - node_modules
  - "**/dist"
  - "**/*.generated.ts"
  - "**/generated/index.ts"
  - "**/*.d.ts"
  - ".next"
overrides:
  - files:
      - "**/*.js"
      - "**/*.cjs"
      - "**/*.mjs"
    rules:
      "@typescript-eslint/no-var-requires": "off"
  - files:
      - "**/*.ts"
      - "**/*.cts"
      - "**/*.mts"
    rules:
      no-dupe-class-members: "off"
      "@typescript-eslint/explicit-member-accessibility": error
      "@typescript-eslint/array-type": error
      "@typescript-eslint/explicit-function-return-type":
        - error
        - allowExpressions: true
          allowHigherOrderFunctions: true
          allowTypedFunctionExpressions: true
          allowDirectConstAssertionInArrowFunctions: true
      "@typescript-eslint/naming-convention":
        - error
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allowSingleOrDouble
        - selector: variable
          format:
            - camelCase
            - UPPER_CASE
            - PascalCase
          leadingUnderscore: allowSingleOrDouble
        - selector: typeLike
          format:
            - PascalCase
        - selector: variable
          modifiers:
            - destructured
          format:
        - selector: objectLiteralProperty
          format:
      "@typescript-eslint/no-empty-interface": "off"
      "@typescript-eslint/no-explicit-any": "off"
      "@typescript-eslint/no-unused-expressions":
        - error
      "@typescript-eslint/no-unused-vars":
        - error
        - args: after-used
          argsIgnorePattern: "^_"
          ignoreRestSiblings: true
      "@typescript-eslint/no-use-before-define":
        - error
        - typedefs: false
      "@typescript-eslint/quotes":
        - error
        - double
        - avoidEscape: true
      "@typescript-eslint/no-redeclare":
        - error
        - ignoreDeclarationMerge: true
      "@typescript-eslint/consistent-type-imports": error
      "@typescript-eslint/method-signature-style": error
      "@typescript-eslint/no-useless-empty-export": error
      "no-invalid-this": "off"
  - files:
      - "src/plugin/graphql/schema/type/index.ts"
    rules:
      "@typescript-eslint/naming-convention":
        - error
        - selector: typeProperty
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allowSingleOrDouble
        - selector: variable
          format:
            - camelCase
            - UPPER_CASE
            - PascalCase
          leadingUnderscore: allowSingleOrDouble
        - selector: typeLike
          format:
            - PascalCase
        - selector: variable
          modifiers:
            - destructured
          format:
        - selector: objectLiteralProperty
          format:
